% Script generated by Brainstorm (28-Jan-2015)

% Input files
sFiles = {...
    'bildc3092/213/data_213_average_150218_0351.mat'};
sFiles2 = {...
    'bildc3092/114/data_114_average_150218_0351.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Difference of means
sFiles = bst_process('CallProcess', 'process_diff_ab', ...
    sFiles, sFiles2);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

% Input files
sFiles = {...
    '/Users/zqi/Documents/MIT/MEG/brainstorm_db/MMN/data/bildc3092/122/data_122_average_150218_0351.mat'
};
sFiles2 = {...
    'bildc3092/114/data_114_average_*.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Difference of means
sFiles = bst_process('CallProcess', 'process_diff_ab', ...
    sFiles, sFiles2);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
